"platformName": "Android"
"appium:automationName": "UiAutomator2"
"appium:deviceName": "Magic5 Pro"
"appium:appPackage": "com.saucelabs.mydemoapp.rn"
"appium:appActivity": "com.saucelabs.mydemoapp.rn.MainActivity"
"appium:dontStopAppOnReset": True
"appium:noReset": True
"appium:ensureWebviewsHavePages": True
"appium:nativeWebScreenshot": True
"appium:newCommandTimeout": 3600
"appium:connectHardwareKeyboard": True